version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssW0rd
      MYSQL_DATABASE: clientdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: express-api-server
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://user:user_password@db/clientdb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynet

  frontend:
    build:
      context: ./Client
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - mynet

volumes:
  db_data:

networks:
  mynet:
