# Use the official Node.js image.
FROM node:16

# Set working directory.
WORKDIR /usr/src/app

# Copy package.json and install dependencies.
COPY package*.json ./
RUN npm install



# Copy the rest of the application code.
COPY . .

# Expose the port the app runs on.
EXPOSE 8080

# Start the Express.js app.
CMD ["npm", "start"]
